### ISSUE TITLE
fails edge case

### ISSUE THREAD

**Issue by danbf** [EvanK/aws-eventbridge-schedule-expressions-regex#1]
Hey,

This is great, but currently fails `0 0 1 JAN-MAR/2 ? *`, which is valid :( .

**Comment by EvanK** [comment]
The AWS scheduler _appears_ to ignore the `/2` entirely, and interpret it as identical to `0 0 1 JAN-MAR ? *`, for what its worth.

Seems like it should be 🤞 a simple enough fix, thanks for reporting.

![image](https://github.com/EvanK/aws-eventbridge-schedule-expressions-regex/assets/84145/ec6517ba-2d30-41b0-93e2-3da8fb8acf4d)

**Comment by danbf** [comment]
thank you.  troubled to see that they fail to parse that correctly
